// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3IbiZvNWXtdWs0bIhKjW6gE_pHD6BVk0',
    appId: '1:447002052350:web:1d443e63d1f028bd3dc7af',
    messagingSenderId: '447002052350',
    projectId: 'gym-sas',
    authDomain: 'gym-sas.firebaseapp.com',
    storageBucket: 'gym-sas.firebasestorage.app',
    measurementId: 'G-DVDXEGSHB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEtC8oH0Zi_cehn8_Sxrc16IjLNVaEng',
    appId: '1:447002052350:android:41543452dfc9f2653dc7af',
    messagingSenderId: '447002052350',
    projectId: 'gym-sas',
    storageBucket: 'gym-sas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKF6RSqldx7TqOaCKl4RYOltbYEJf7QOs',
    appId: '1:447002052350:ios:3447643f112c88d03dc7af',
    messagingSenderId: '447002052350',
    projectId: 'gym-sas',
    storageBucket: 'gym-sas.firebasestorage.app',
    iosBundleId: 'pt.nxtperformancestudio.app',
  );
}
